ci: Allocate mode storage space
Signed-off-by: Yuya Hamamachi <yuya.hamamachi.sx@renesas.com>

diff --git a/.github/workflows/build_bsp_sparrow-hawk.yaml b/.github/workflows/build_bsp_sparrow-hawk.yaml
--- a/.github/workflows/build_bsp_sparrow-hawk.yaml
+++ b/.github/workflows/build_bsp_sparrow-hawk.yaml
@@ -13,44 +13,111 @@ jobs:
     name: Build
     runs-on: ubuntu-22.04
     steps:
+      - name: Aggressive cleanup
+        # Based on https://github.com/NobuoTsukamoto/my_actions_test/blob/8f1ad38e225730322f196da7d958d0cfd49eca01/.github/workflows/test_contains.yml
+        run: |
+          df -h
+          sudo rm -rf "/home/work/*" || true
+          sudo rm -rf "/opt/*" || true
+          sudo rm -rf "/usr/local/share/*" || true
+          sudo rm -rf "/usr/share/dotnet" || true
+          sudo rm -rf "$AGENT_TOOLSDIRECTORY" || true
+          sudo rm -rf "/usr/local/lib/android" || true
+          sudo rm -rf "/usr/lib/jvm" || true
+          sudo rm -rf "/usr/share/swift" || true
+          sudo rm -rf "/usr/local/julia*" || true
+          sudo rm -rf "/usr/share/kotlinc" || true
+          sudo rm -rf "/usr/share/miniconda" || true
+          sudo rm -rf "/usr/share/sbt" || true
+          sudo rm -rf "/usr/local/sqlpackage" || true
+          sudo rm -rf "/usr/bin/yq" || true
+          sudo rm -rf "/usr/local/bin/terraform" || true
+          sudo rm -rf "/usr/local/bin/stack" || true
+          sudo rm -rf "/usr/local/bin/aliyun" || true
+          sudo rm -rf "/usr/local/bin/pulumi" || true
+          sudo rm -rf "/usr/local/bin/pulumi-language-dotnet" || true
+          sudo rm -rf "/usr/local/bin/azcopy" || true
+          sudo rm -rf "/usr/local/aws-cli" || true
+          sudo rm -rf "/usr/local/bin/bicep" || true
+          sudo rm -rf "/usr/local/bin/rebar3" || true
+          sudo rm -rf "/usr/local/bin/phpunit" || true
+          sudo rm -rf "/usr/local/bin/packer" || true
+          sudo rm -rf "/usr/local/bin/bicep" || true
+          sudo rm -rf "/usr/local/bin/docker-compose" || true
+          sudo rm -rf "/usr/local/bin/minikube" || true
+          sudo rm -rf "/usr/local/bin/kustomize" || true
+          sudo rm -rf "/usr/local/bin/kubectl" || true
+          sudo rm -rf "/usr/local/bin/kind" || true
+          sudo rm -rf "/usr/local/bin/helm" || true
+          sudo rm -rf "/usr/local/bin/azcopy_11.3.1" || true
+          sudo rm -rf "/usr/local/bin/bicep" || true
+          sudo rm -rf "/usr/local/bin/.ghcup" || true
+          sudo rm -rf "/usr/local/bin/phpunit" || true
+          sudo rm -rf "/usr/local/bin/pulumi-*" || true
+          sudo rm -rf "/usr/local/bin/oc" || true
+          sudo rm -rf "/usr/local/bin/ctest" || true
+          sudo rm -rf "/usr/local/bin/cmake-gui" || true
+          sudo rm -rf "/usr/local/bin/ccmake" || true
+          sudo rm -rf "/usr/local/bin/cpack" || true
+          sudo rm -rf "/usr/local/bin/oras" || true
+          sudo rm -rf "/home/.dotnet/tools" || true
+          sudo rm -rf "/home/linuxbrew" || true
+          sudo rm -rf "/home/.nvm" || true
+          sudo rm -rf "/home/perflog" || true
+          sudo rm -rf "/etc/skel/.dotnet/tools" || true
+          sudo rm -rf "/usr/share/apache-maven-3.8.8" || true
+          sudo rm -rf "/usr/share/gradle-8.7" || true
+          sudo rm -rf "/usr/local/.ghcup" || true
+          sudo rm -rf "/usr/bin/composer" || true
+          sudo rm -rf "/usr/libexec/docker/cli-plugins" || true
+          sudo rm -rf "/usr/bin/docker-credential-ecr-login" || true
+          sudo rm -rf "/usr/local/lib/lein" || true
+          sudo docker image prune --all --force
+          sudo npm uninstall bazel || true
+          sudo npm uninstall bazelisk || true
+          rustup self uninstall -y
+          ls -al /usr/local/share
+          df -h
+      - name: Remove more packages
+        # Based on https://github.com/easimon/maximize-build-space/issues/30
+        run: |
+          removePackages=`apt list --manual-installed | awk '{print $1}' | sed 's|\(.*\)/.*|\1|' | grep -E -v 'base*|bash|binutils|bsdutils|bzip2|ca-certificates|coreutils|curl|dbus|diffutils|dpkg*|file|findutils|git*|grep|gzip|hostname|init|iproute2|iputils-ping|keyutils|lib*|linux-headers*|linux-image*|lld*|locales|login|lsb-release|make|net-tools|openssh-*|openssl|patchelf|rpm|rsync|session-manager-plugin|shellcheck|ssh|sudo|sysvinit-utils|tar|tcl*|time|tk|tzdata|ubuntu-*|unzip|upx-ucl|walinuxagent|wget|xz-utils|zip*|zsync|apt|dash|ncurses-bin|shim-signed|grub-efi-*|mokutil|sbsigntool|secureboot-db|docker-*|containerd.io' | tr '\n' ' '`
+          echo "Removing following userinstalled packages: $removePackages"
+          sudo apt-get purge -y $removePackages
+          sudo dpkg -r packages-microsoft-prod > /dev/null 2>&1 || true
+          sudo apt-get autoremove -y > /dev/null 2>&1 || true
+          sudo apt-get autoclean -y > /dev/null 2>&1 || true
+          df -h
+      - name: Setup package
+        run: |
+          sudo apt update
+          sudo apt install -y \
+            build-essential chrpath cpio debianutils diffstat file gawk gcc git iputils-ping \
+            libacl1 liblz4-tool locales python3 python3-git python3-jinja2 python3-pexpect \
+            python3-pip python3-subunit socat texinfo unzip wget xz-utils zstd device-tree-compiler
+          sudo apt-get install -y \
+            lvm2
+          # Clean up apt
+          sudo apt autoremove -y
+          sudo apt clean -y
+          sudo apt autoclean -y
+          # For using --sstate-mirror option
+          pip3 install websockets
+          df -h
+
       - name: Maximize build space
-        uses: easimon/maximize-build-space@v7
+        uses: easimon/maximize-build-space@master
         with:
-          root-reserve-mb: 4096
-          swap-size-mb: 1024
+          root-reserve-mb: 512
+          swap-size-mb: 512
           remove-dotnet: 'true'
           remove-android: 'true'
           remove-haskell: 'true'
           remove-codeql: 'true'
           remove-docker-images: 'true'
 
-      - uses: actions/checkout@v3
-      - name: Setup package
-        run: |
-          sudo apt update
-          sudo apt install -y \
-          gawk wget git-core diffstat unzip texinfo gcc-multilib \
-          build-essential chrpath socat cpio python3 python3-pip python3-pexpect \
-          xz-utils debianutils iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev \
-          xterm locales curl vim sudo rsync bc \
-          \
-          openjdk-8-jdk git-core gnupg flex bison \
-          gperf build-essential zip curl zlib1g-dev gcc-multilib ccache \
-          g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev \
-          libx11-dev lib32z-dev libgl1-mesa-dev libxml2-utils liblz4-tool \
-          xsltproc unzip python3-networkx python3-wand liblz4-tool bc \
-          apt-transport-https ca-certificates ninja-build \
-          ninja-build dosfstools libncurses-dev flex bison \
-          screen libncurses-dev ninja-build dosfstools \
-          python3-pygit2 python3-venv python3-pyelftools protobuf-compiler gperf pigz \
-          zstd simg2img libncurses5 python3-pycryptodome libssl-dev lzop \
-          lld libelf-dev dwarves openjdk-11-jdk pigz cmake file device-tree-compiler \
-
-          # Clean up apt
-          sudo apt autoremove -y
-          sudo apt clean -y
-          sudo apt autoclean -y
-          pip3 install websockets
+      - name: Checkout repository
+        uses: actions/checkout@v3
 
       - name: Check disk and memory
         run: |
